name: 'dbt_course_practice'
version: '1.0.0'
profile: 'dbt_course_practice'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  dbt_course_practice:
    +post-hook:
      - |
          CREATE SCHEMA IF NOT EXISTS logs;

          CREATE TABLE IF NOT EXISTS logs.dbt_logs (
              event_date timestamp,
              event_name varchar(100),
              node_name varchar(256)
          );

          INSERT INTO logs.dbt_logs
          (event_date, event_name, node_name)
          VALUES (
              CURRENT_TIMESTAMP,
              'finish run model',
              '{{ model.name }}'
          );

      - "{{ check_dependencies() }}"
      
    staging:
      +tags: ['staging'] 
      flights:
        +meta:
          owner: "dbt_project_yml@gmail.com"
          year_created: 2026
    intermediate: 
      +tags: ['intermediate']

seeds:
  dbt_course_practice:
    schema: seeds
