name: 'dbt_course_practice'
version: '1.0.0'
profile: 'dbt_course_practice'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_course_practice:
    staging:
      +tags: ['staging'] 
      flights:
        +meta:
          owner: "dbt_project_yml@gmail.com"
          year_created: 2026
    intermediate: 
      +tags: ['intermediate']

seeds:
  dbt_course_practice:
    schema: seeds
